apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: basic-nginx
spec:
  selector:
    matchLabels:
      app: basic-nginx
      tier: frontend
  replicas: 3
  template:
    metadata:
      labels:
        app: basic-nginx
        tier: frontend
    spec:
      containers:
      - name: nginxv1
        image: docker.io/call900913/basic-nginx:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: basic-nginx
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: basic-nginx
    tier: frontend
